"""
Column indices for .azr file parsing.
"""

# Level row indices
J_INDEX = 0
PI_INDEX = 1
ENERGY_INDEX = 2
ENERGY_FIXED_INDEX = 3
CHANNEL_INDEX = 5
LEVEL_INCLUDE_INDEX = 9
WIDTH_FIXED_INDEX = 10
WIDTH_INDEX = 11
SEPARATION_ENERGY_INDEX = 21
CHANNEL_RADIUS_INDEX = 27

# Data segment indices
DATA_INCLUDE_INDEX = 0
DATA_IN_CHANNEL_INDEX = 1
DATA_OUT_CHANNEL_INDEX = 2
DATA_NORM_FACTOR_INDEX = 8
DATA_VARY_NORM_INDEX = 9
DATA_FILEPATH_INDEX = 11

# Config section indices
OUTPUT_DIR_INDEX = 2  # line index inside <config>
